import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import productsRouter from "./products";
import customersRouter from "./customers";
import ordersRouter from "./orders";
import bookingsRouter from "./bookings";
import whatsappRouter from "./whatsapp";
import settingsRouter from "./settings";
import statsRouter from "./stats";
import customerAuthRouter from "./customer-auth";
import myOrdersRouter from "./my-orders";
import paymentsRouter from "./payments";
import couponsRouter from "./coupons";
import affiliatesRouter from "./affiliates";
import campaignsRouter from "./campaigns";
import employeesRouter from "./employees";
import categoriesRouter from "./categories";
import bannersRouter from "./banners";
import bankAccountsRouter from "./bank-accounts";
import productImportRouter from "./product-import";
import assistantRouter from "./assistant";
import storageRouter from "./storage";
import designRouter from "./design";
import aiTestRouter from "./ai-test";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(productsRouter);
router.use(customersRouter);
router.use(ordersRouter);
router.use(bookingsRouter);
router.use(whatsappRouter);
router.use(settingsRouter);
router.use(statsRouter);
router.use(customerAuthRouter);
router.use(myOrdersRouter);
router.use(paymentsRouter);
router.use(couponsRouter);
router.use(affiliatesRouter);
router.use(campaignsRouter);
router.use(employeesRouter);
router.use(categoriesRouter);
router.use(bannersRouter);
router.use(bankAccountsRouter);
router.use(productImportRouter);
router.use(storageRouter);
router.use(assistantRouter);
router.use(designRouter);
router.use(aiTestRouter);

export default router;
